In [40]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

## Max Pooling

In [41]:
max_1_2019 = pd.read_csv("../results/v2.5/max/2019_max_results_v1.1.csv")
max_2_2019 = pd.read_csv("../results/v2.5/max/2019_max_results_v1.2.csv")
max_3_2019 = pd.read_csv("../results/v2.5/max/2019_max_results_v1.3.csv")
max_4_2019 = pd.read_csv("../results/v2.5/max/2019_max_results_v1.4.csv")
max_5_2019 = pd.read_csv("../results/v2.5/max/2019_max_results_v1.5.csv")

max_1_2021 = pd.read_csv("../results/v2.5/max/2021_max_results_v1.1.csv")
max_2_2021 = pd.read_csv("../results/v2.5/max/2021_max_results_v1.2.csv")
max_3_2021 = pd.read_csv("../results/v2.5/max/2021_max_results_v1.3.csv")
max_4_2021 = pd.read_csv("../results/v2.5/max/2021_max_results_v1.4.csv")
max_5_2021 = pd.read_csv("../results/v2.5/max/2021_max_results_v1.5.csv")

In [42]:
max_2019 = pd.concat([max_1_2019, max_2_2019, max_3_2019, max_4_2019, max_5_2019])
max_2021 = pd.concat([max_1_2021, max_2_2021, max_3_2021, max_4_2021, max_5_2021])

In [43]:
final_2019_max_result = pd.DataFrame({"dataset": ["ASVspoof 2019"], "eer_mean": [max_2019["eer"].mean()], "eer_std": [max_2019["eer"].std()]})
final_2021_max_result = pd.DataFrame({"dataset": ["ASVspoof 2021"], "eer_mean": [max_2021["eer"].mean()], "eer_std": [max_2021["eer"].std()]})

In [44]:
final_2019_max_result

         dataset  eer_mean  eer_std
0  ASVspoof 2019  0.067276  0.00317

## Average Pooling

In [45]:
average_1_2019 = pd.read_csv("../results/v2.5/average/2019_average_results_v1.1.csv")
average_2_2019 = pd.read_csv("../results/v2.5/average/2019_average_results_v1.2.csv")
average_3_2019 = pd.read_csv("../results/v2.5/average/2019_average_results_v1.3.csv")
average_4_2019 = pd.read_csv("../results/v2.5/average/2019_average_results_v1.4.csv")
average_5_2019 = pd.read_csv("../results/v2.5/average/2019_average_results_v1.5.csv")

average_1_2021 = pd.read_csv("../results/v2.5/average/2021_average_results_v1.1.csv")
average_2_2021 = pd.read_csv("../results/v2.5/average/2021_average_results_v1.2.csv")
average_3_2021 = pd.read_csv("../results/v2.5/average/2021_average_results_v1.3.csv")
average_4_2021 = pd.read_csv("../results/v2.5/average/2021_average_results_v1.4.csv")
average_5_2021 = pd.read_csv("../results/v2.5/average/2021_average_results_v1.5.csv")

In [46]:
average_2019 = pd.concat([average_1_2019, average_2_2019, average_3_2019, average_4_2019, average_5_2019])
average_2021 = pd.concat([average_1_2021, average_2_2021, average_3_2021, average_4_2021, average_5_2021])

In [47]:
final_2019_average_result = pd.DataFrame({"dataset": ["ASVspoof 2019"], "eer_mean": [average_2019["eer"].mean()], "eer_std": [average_2019["eer"].std()]})
final_2021_average_result = pd.DataFrame({"dataset": ["ASVspoof 2021"], "eer_mean": [average_2021["eer"].mean()], "eer_std": [average_2021["eer"].std()]})

In [48]:
final_2019_average_result

         dataset  eer_mean   eer_std
0  ASVspoof 2019   0.06798  0.004993

## Wavelet Pooling

In [49]:
wavelets_1_2019 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.1/2019_wavelet_results.csv")
wavelets_2_2019 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.2/2019_wavelet_results.csv")
wavelets_3_2019 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.3/2019_wavelet_results.csv")
wavelets_4_2019 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.4/2019_wavelet_results.csv")
wavelets_5_2019 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.5/2019_wavelet_results.csv")

wavelets_1_2021 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.1/2021_wavelet_results.csv")
wavelets_2_2021 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.2/2021_wavelet_results.csv")
wavelets_3_2021 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.3/2021_wavelet_results.csv")
wavelets_4_2021 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.4/2021_wavelet_results.csv")
wavelets_5_2021 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.5/2021_wavelet_results.csv")

In [50]:
wavelets_2019 = pd.concat([wavelets_1_2019, wavelets_2_2019, wavelets_3_2019, wavelets_4_2019, wavelets_5_2019])
wavelets_2021 = pd.concat([wavelets_1_2021, wavelets_2_2021, wavelets_3_2021, wavelets_4_2021, wavelets_5_2021])

In [51]:
final_2019_wavelet_result = (
    wavelets_2019.groupby(["dataset", "wavelet_family"])
      .agg(eer_mean=("eer", "mean"),
           eer_std=("eer", "std"))
      .reset_index()
      .sort_values(["dataset", "eer_mean"])
)
final_2021_wavelet_result = (
    wavelets_2021.groupby(["dataset", "wavelet_family"])
      .agg(eer_mean=("eer", "mean"),
           eer_std=("eer", "std"))
      .reset_index()
      .sort_values(["dataset", "eer_mean"])
)

In [52]:
final_2019_wavelet_result

          dataset wavelet_family  eer_mean   eer_std
10  ASVspoof 2019            db6  0.063962  0.004594
3   ASVspoof 2019           db24  0.064539  0.002622
9   ASVspoof 2019            db4  0.064548  0.004702
5   ASVspoof 2019           db28  0.067753  0.007228
0   ASVspoof 2019           db14  0.068764  0.008270
4   ASVspoof 2019           db26  0.069072  0.015889
11  ASVspoof 2019            db8  0.069502  0.010813
1   ASVspoof 2019           db16  0.069944  0.004190
2   ASVspoof 2019           db18  0.070055  0.014129
8   ASVspoof 2019           db38  0.070487  0.006000
6   ASVspoof 2019           db34  0.071458  0.005514
7   ASVspoof 2019           db36  0.075064  0.006415

## Final Results

In [56]:
max_2019_aligned = final_2019_max_result.assign(
    method="Max"
)

average_2019_aligned = final_2019_average_result.assign(
    method="Average"
)

wavelet_2019_aligned = final_2019_wavelet_result.rename(
    columns={"wavelet_family": "method"}
)

final_2019 = pd.concat(
    [wavelet_2019_aligned, average_2019_aligned, max_2019_aligned],
    ignore_index=True,
).sort_values(["dataset", "eer_mean"])

In [59]:
max_2021_aligned = final_2021_max_result.assign(
    method="Max"
)

average_2021_aligned = final_2021_average_result.assign(
    method="Average"
)

wavelet_2021_aligned = final_2021_wavelet_result.rename(
    columns={"wavelet_family": "method"}
)

final_2021 = pd.concat(
    [wavelet_2021_aligned, average_2021_aligned, max_2021_aligned],
    ignore_index=True,
).sort_values(["dataset", "eer_mean"])

In [61]:
final_2019.to_csv("../results/v2.5/final_results_five_seeds_2019.csv", index=False)
final_2021.to_csv("../results/v2.5/final_results_five_seeds_2021.csv", index=False)