In [127]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

## Max Pooling

In [128]:
max_1_2019 = pd.read_csv("../results/v2.5/max/2019_max_results_v1.1.csv").assign(seed=42, wavelet_family="Max")
max_2_2019 = pd.read_csv("../results/v2.5/max/2019_max_results_v1.2.csv").assign(seed=51, wavelet_family="Max")
max_3_2019 = pd.read_csv("../results/v2.5/max/2019_max_results_v1.3.csv").assign(seed=73, wavelet_family="Max")
max_4_2019 = pd.read_csv("../results/v2.5/max/2019_max_results_v1.4.csv").assign(seed=69, wavelet_family="Max")
max_5_2019 = pd.read_csv("../results/v2.5/max/2019_max_results_v1.5.csv").assign(seed=49, wavelet_family="Max")

max_1_2021 = pd.read_csv("../results/v2.5/max/2021_max_results_v1.1.csv").assign(seed=42, wavelet_family="Max")
max_2_2021 = pd.read_csv("../results/v2.5/max/2021_max_results_v1.2.csv").assign(seed=51, wavelet_family="Max")
max_3_2021 = pd.read_csv("../results/v2.5/max/2021_max_results_v1.3.csv").assign(seed=73, wavelet_family="Max")
max_4_2021 = pd.read_csv("../results/v2.5/max/2021_max_results_v1.4.csv").assign(seed=69, wavelet_family="Max")
max_5_2021 = pd.read_csv("../results/v2.5/max/2021_max_results_v1.5.csv").assign(seed=49, wavelet_family="Max")

In [129]:
max_2019 = pd.concat([max_1_2019, max_2_2019, max_3_2019, max_4_2019, max_5_2019])
max_2021 = pd.concat([max_1_2021, max_2_2021, max_3_2021, max_4_2021, max_5_2021])

In [130]:
new_max_2019 = max_2019.drop("roc_auc", axis=1)
new_max_2019.columns = ['dataset', 'eer', 'seed', 'wavelet_family']
new_max_2019.to_csv("../results/v2.5/max_results_grouped_2019.csv", index=False)

In [131]:
new_max_2021 = max_2021.drop("roc_auc", axis=1)
new_max_2021.columns = ['dataset', 'eer', 'seed', 'wavelet_family']
new_max_2021.to_csv("../results/v2.5/max_results_grouped_2021.csv", index=False)

In [132]:
final_2019_max_result = pd.DataFrame({"dataset": ["ASVspoof 2019"], "eer_mean": [max_2019["eer"].mean()], "eer_std": [max_2019["eer"].std()]})
final_2021_max_result = pd.DataFrame({"dataset": ["ASVspoof 2021"], "eer_mean": [max_2021["eer"].mean()], "eer_std": [max_2021["eer"].std()]})

In [133]:
final_2019_max_result

         dataset  eer_mean  eer_std
0  ASVspoof 2019  0.067276  0.00317

## Average Pooling

In [134]:
average_1_2019 = pd.read_csv("../results/v2.5/average/2019_average_results_v1.1.csv").assign(seed=42, wavelet_family="Average")
average_2_2019 = pd.read_csv("../results/v2.5/average/2019_average_results_v1.2.csv").assign(seed=51, wavelet_family="Average")
average_3_2019 = pd.read_csv("../results/v2.5/average/2019_average_results_v1.3.csv").assign(seed=73, wavelet_family="Average")
average_4_2019 = pd.read_csv("../results/v2.5/average/2019_average_results_v1.4.csv").assign(seed=69, wavelet_family="Average")
average_5_2019 = pd.read_csv("../results/v2.5/average/2019_average_results_v1.5.csv").assign(seed=49, wavelet_family="Average")

average_1_2021 = pd.read_csv("../results/v2.5/average/2021_average_results_v1.1.csv").assign(seed=42, wavelet_family="Average")
average_2_2021 = pd.read_csv("../results/v2.5/average/2021_average_results_v1.2.csv").assign(seed=51, wavelet_family="Average")
average_3_2021 = pd.read_csv("../results/v2.5/average/2021_average_results_v1.3.csv").assign(seed=73, wavelet_family="Average")
average_4_2021 = pd.read_csv("../results/v2.5/average/2021_average_results_v1.4.csv").assign(seed=69, wavelet_family="Average")
average_5_2021 = pd.read_csv("../results/v2.5/average/2021_average_results_v1.5.csv").assign(seed=49, wavelet_family="Average")

In [135]:
average_2019 = pd.concat([average_1_2019, average_2_2019, average_3_2019, average_4_2019, average_5_2019])
average_2021 = pd.concat([average_1_2021, average_2_2021, average_3_2021, average_4_2021, average_5_2021])

In [136]:
new_average_2019 = average_2019.drop("roc_auc", axis=1)
new_average_2019.columns = ['dataset', 'eer', 'seed', 'wavelet_family']
new_average_2019.to_csv("../results/v2.5/average_results_grouped_2019.csv", index=False)

In [137]:
new_average_2021 = average_2021.drop("roc_auc", axis=1)
new_average_2021.columns = ['dataset', 'eer', 'seed', 'wavelet_family']
new_average_2021.to_csv("../results/v2.5/average_results_grouped_2021.csv", index=False)

In [138]:
final_2019_average_result = pd.DataFrame({"dataset": ["ASVspoof 2019"], "eer_mean": [average_2019["eer"].mean()], "eer_std": [average_2019["eer"].std()]})
final_2021_average_result = pd.DataFrame({"dataset": ["ASVspoof 2021"], "eer_mean": [average_2021["eer"].mean()], "eer_std": [average_2021["eer"].std()]})

In [139]:
final_2019_average_result

         dataset  eer_mean   eer_std
0  ASVspoof 2019   0.06798  0.004993

## Wavelet Pooling

In [140]:
wavelets_1_2019 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.1/2019_wavelet_results.csv").assign(seed=42)
wavelets_2_2019 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.2/2019_wavelet_results.csv").assign(seed=51)
wavelets_3_2019 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.3/2019_wavelet_results.csv").assign(seed=73)
wavelets_4_2019 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.4/2019_wavelet_results.csv").assign(seed=69)
wavelets_5_2019 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.5/2019_wavelet_results.csv").assign(seed=49)

wavelets_1_2021 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.1/2021_wavelet_results.csv").assign(seed=42)
wavelets_2_2021 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.2/2021_wavelet_results.csv").assign(seed=51)
wavelets_3_2021 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.3/2021_wavelet_results.csv").assign(seed=73)
wavelets_4_2021 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.4/2021_wavelet_results.csv").assign(seed=69)
wavelets_5_2021 = pd.read_csv("../results/v2.5/wavelets/wavelet_results_v1.5/2021_wavelet_results.csv").assign(seed=49)

In [141]:
wavelets_2019 = pd.concat([wavelets_1_2019, wavelets_2_2019, wavelets_3_2019, wavelets_4_2019, wavelets_5_2019])
wavelets_2021 = pd.concat([wavelets_1_2021, wavelets_2_2021, wavelets_3_2021, wavelets_4_2021, wavelets_5_2021])

In [142]:
new_wavelets_2019 = wavelets_2019.drop("roc_auc", axis=1)
new_wavelets_2019.columns = ['dataset', 'wavelet_family', 'eer', 'seed']
new_wavelets_2019.to_csv("../results/v2.5/wavelets_results_grouped_2019.csv", index=False)

In [143]:
new_wavelets_2021 = wavelets_2021.drop("roc_auc", axis=1)
new_wavelets_2021.columns = ['dataset', 'wavelet_family', 'eer', 'seed']
new_wavelets_2021.to_csv("../results/v2.5/wavelets_results_grouped_2021.csv", index=False)

In [144]:
final_2019_wavelet_result = (
    wavelets_2019.groupby(["dataset", "wavelet_family"])
      .agg(eer_mean=("eer", "mean"),
           eer_std=("eer", "std"))
      .reset_index()
      .sort_values(["dataset", "eer_mean"])
)
final_2021_wavelet_result = (
    wavelets_2021.groupby(["dataset", "wavelet_family"])
      .agg(eer_mean=("eer", "mean"),
           eer_std=("eer", "std"))
      .reset_index()
      .sort_values(["dataset", "eer_mean"])
)

In [145]:
final_2019_wavelet_result

          dataset wavelet_family  eer_mean   eer_std
10  ASVspoof 2019            db6  0.065187  0.003996
9   ASVspoof 2019            db4  0.065992  0.005925
3   ASVspoof 2019           db24  0.066956  0.005314
11  ASVspoof 2019            db8  0.067267  0.011053
5   ASVspoof 2019           db28  0.067858  0.007266
6   ASVspoof 2019           db34  0.067873  0.003732
0   ASVspoof 2019           db14  0.070204  0.007637
2   ASVspoof 2019           db18  0.070510  0.013990
8   ASVspoof 2019           db38  0.071271  0.007047
4   ASVspoof 2019           db26  0.071510  0.015330
7   ASVspoof 2019           db36  0.072453  0.011141
1   ASVspoof 2019           db16  0.073022  0.005654

## Final Results

In [146]:
max_2019_aligned = final_2019_max_result.assign(
    method="Max"
)

average_2019_aligned = final_2019_average_result.assign(
    method="Average"
)

wavelet_2019_aligned = final_2019_wavelet_result.rename(
    columns={"wavelet_family": "method"}
)

final_2019 = pd.concat(
    [wavelet_2019_aligned, average_2019_aligned, max_2019_aligned],
    ignore_index=True,
).sort_values(["dataset", "eer_mean"])

In [147]:
max_2021_aligned = final_2021_max_result.assign(
    method="Max"
)

average_2021_aligned = final_2021_average_result.assign(
    method="Average"
)

wavelet_2021_aligned = final_2021_wavelet_result.rename(
    columns={"wavelet_family": "method"}
)

final_2021 = pd.concat(
    [wavelet_2021_aligned, average_2021_aligned, max_2021_aligned],
    ignore_index=True,
).sort_values(["dataset", "eer_mean"])

In [148]:
final_2019.to_csv("../results/v2.5/final_results_five_seeds_2019.csv", index=False)
final_2021.to_csv("../results/v2.5/final_results_five_seeds_2021.csv", index=False)