In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from autorank import autorank, plot_stats, create_report, latex_table

from scipy import stats
import scikit_posthocs as sp

In [2]:
wavelet_2019 = pd.read_csv("../results/v2.5/wavelets_results_grouped_2019.csv")
max_2019 = pd.read_csv("../results/v2.5/max_results_grouped_2019.csv")
average_2019 = pd.read_csv("../results/v2.5/average_results_grouped_2019.csv")

In [3]:
model_results_2019 = pd.concat([wavelet_2019, max_2019, average_2019])

In [4]:
autorank_input_2019 = model_results_2019.pivot(index='seed', columns='wavelet_family', values='eer')
autorank_input_2019

wavelet_family,Average,Max,db14,db16,db18,db24,db26,db28,db34,db36,db38,db4,db6,db8
seed,,,,,,,,,,,,,,
32,0.070981,0.083105,0.061163,0.081967,0.063248,0.067952,0.061456,0.069782,0.069913,0.077255,0.067299,0.082943,0.061863,0.062971
42,0.062101,0.068806,0.074591,0.076720,0.060847,0.069065,0.058192,0.062396,0.068282,0.074434,0.074825,0.059203,0.070787,0.086597
49,0.072603,0.068113,0.070289,0.081052,0.067983,0.075325,0.073525,0.070158,0.062540,0.054522,0.079807,0.072480,0.065961,0.061856
51,0.064039,0.069605,0.060367,0.067573,0.078722,0.062428,0.073148,0.058328,0.067186,0.083073,0.068525,0.060487,0.060095,0.061191
69,0.073295,0.068145,0.080060,0.069474,0.055067,0.064332,0.057512,0.075740,0.073011,0.070427,0.061033,0.067299,0.062939,0.060341
73,0.067860,0.061709,0.065715,0.070292,0.089931,0.063630,0.095173,0.072665,0.068345,0.079810,0.072164,0.070489,0.066153,0.066349
99,0.065914,0.062240,0.080491,0.064285,0.064723,0.065669,0.067998,0.065368,0.069759,0.071796,0.063655,0.068644,0.066207,0.064585
101,0.077532,0.075325,0.077908,0.076547,0.070289,0.068691,0.070835,0.074395,0.073695,0.088363,0.077223,0.066076,0.070182,0.062801

In [5]:
wavelet_2021= pd.read_csv("../results/v2.5/wavelets_results_grouped_2021.csv")
max_2021 = pd.read_csv("../results/v2.5/max_results_grouped_2021.csv")
average_2021= pd.read_csv("../results/v2.5/average_results_grouped_2021.csv")

In [6]:
model_results_2021 = pd.concat([wavelet_2021, max_2021, average_2021])

In [7]:
autorank_input_2021 = model_results_2021.pivot(index='seed', columns='wavelet_family', values='eer')
autorank_input_2021

wavelet_family,Average,Max,db14,db16,db18,db24,db26,db28,db34,db36,db38,db4,db6,db8
seed,,,,,,,,,,,,,,
32,0.139828,0.149577,0.154835,0.150558,0.144795,0.146108,0.144157,0.156081,0.153632,0.157056,0.158140,0.161661,0.146481,0.147080
42,0.144482,0.151421,0.150827,0.171162,0.144158,0.153804,0.143616,0.149252,0.145181,0.147670,0.152458,0.148626,0.165927,0.174290
49,0.146332,0.142815,0.151366,0.159492,0.156950,0.150336,0.150127,0.150172,0.143890,0.143292,0.167354,0.160689,0.145132,0.166051
51,0.142802,0.147517,0.137871,0.146462,0.149523,0.142189,0.159992,0.153635,0.174561,0.193421,0.142803,0.152883,0.152636,0.140276
69,0.154185,0.150239,0.148331,0.148435,0.143507,0.144437,0.141074,0.151801,0.158031,0.156731,0.143073,0.143893,0.149422,0.141666
73,0.143346,0.149310,0.152233,0.151041,0.169489,0.141000,0.162414,0.159968,0.150845,0.147670,0.149693,0.142771,0.143291,0.143654
99,0.140949,0.143128,0.153544,0.143778,0.142098,0.160188,0.147137,0.175745,0.161379,0.150063,0.160732,0.147572,0.140743,0.149416
101,0.154562,0.150391,0.148073,0.171145,0.151205,0.143188,0.143292,0.163010,0.150707,0.156297,0.161825,0.144157,0.150877,0.150342

## AutoRank

### ASVspoof 2019

In [8]:
result_2019 = autorank(autorank_input_2019, alpha=0.05, verbose=False, order='ascending')
print(result_2019)

         meanrank    median       mad  ci_lower  ci_upper effect_size  \
db8         4.750  0.062886  0.001697  0.060341  0.086597         0.0
db6         5.000  0.066057  0.003621  0.060095  0.070787    -0.75643
db18        6.250  0.066353  0.004721  0.055067  0.089931   -0.659214
db24        6.375  0.066810  0.002367  0.062428  0.075325   -1.285378
Max         7.125  0.068475  0.003683  0.061709  0.083105   -1.314844
db4         7.125  0.067971  0.003514  0.059203  0.082943     -1.2431
db26        7.250  0.069417  0.006035  0.057512  0.095173   -0.993765
db28        7.375  0.069970  0.004513  0.058328   0.07574   -1.401535
db34        7.875  0.069052  0.001363   0.06254  0.073695   -2.701969
db14        8.375  0.072440  0.007172  0.060367  0.080491   -1.236454
db38        8.500  0.070345  0.005585  0.061033  0.079807   -1.218818
Average     8.625  0.069421   0.00369  0.062101  0.077532   -1.534568
db16        9.750  0.073420  0.004896  0.064285  0.081967   -1.939086
db36       10.625  0.075844  0.004733  0.054522  0.088363   -2.458547

          magnitude effect_size_above magnitude_above
db8      negligible               0.0      negligible
db6          medium          -0.75643          medium
db18         medium         -0.047424      negligible
db24          large         -0.082556      negligible
Max           large         -0.362805           small
db4           large          0.094458      negligible
db26          large         -0.197469      negligible
db28          large         -0.070087      negligible
db34          large          0.185854      negligible
db14          large         -0.442654           small
db38          large          0.219859           small
Average       large          0.131649      negligible
db16          large         -0.622163          medium
db36          large         -0.339666           small
RankResult(rankdf=
         meanrank    median       mad  ci_lower  ci_upper effect_size  \
db8         4.750  0.062886  0.001697  0.060341  0.086597         0.0
db6         5.000  0.066057  0.003621  0.060095  0.070787    -0.75643
db18        6.250  0.066353  0.004721  0.055067  0.089931   -0.659214
db24        6.375  0.066810  0.002367  0.062428  0.075325   -1.285378
Max         7.125  0.068475  0.003683  0.061709  0.083105   -1.314844
db4         7.125  0.067971  0.003514  0.059203  0.082943     -1.2431
db26        7.250  0.069417  0.006035  0.057512  0.095173   -0.993765
db28        7.375  0.069970  0.004513  0.058328   0.07574   -1.401535
db34        7.875  0.069052  0.001363   0.06254  0.073695   -2.701969
db14        8.375  0.072440  0.007172  0.060367  0.080491   -1.236454
db38        8.500  0.070345  0.005585  0.061033  0.079807   -1.218818
Average     8.625  0.069421   0.00369  0.062101  0.077532   -1.534568
db16        9.750  0.073420  0.004896  0.064285  0.081967   -1.939086
db36       10.625  0.075844  0.004733  0.054522  0.088363   -2.458547

          magnitude effect_size_above magnitude_above
db8      negligible               0.0      negligible
db6          medium          -0.75643          medium
db18         medium         -0.047424      negligible
db24          large         -0.082556      negligible
Max           large         -0.362805           small
db4           large          0.094458      negligible
db26          large         -0.197469      negligible
db28          large         -0.070087      negligible
db34          large          0.185854      negligible
db14          large         -0.442654           small
db38          large          0.219859           small
Average       large          0.131649      negligible
db16          large         -0.622163          medium
db36          large         -0.339666           small
pvalue=0.24912985116586753
cd=7.014879480298086
omnibus=friedman
posthoc=nemenyi
all_normal=False
pvals_shapiro=[np.float64(0.562453342834845), np.float64(0.5768015345647322), np.float64(0.5916547004317363), np.float64(0.5882473275325162), np.float64(0.26867688015892205), np.float64(0.5399163773054878), np.float64(0.13771450391234097), np.float64(0.629603819137722), np.float64(0.6018389773094874), np.float64(0.00031961408782956786), np.float64(0.9028815000631601), np.float64(0.4030341729167488), np.float64(0.2763234072206633), np.float64(0.9177034563241704)]
homoscedastic=True
pval_homogeneity=0.36997922174811354
homogeneity_test=levene
alpha=0.05
alpha_normality=0.0035714285714285718
num_samples=8
posterior_matrix=
None
decision_matrix=
None
rope=None
rope_mode=None
effect_size=akinshin_gamma
force_mode=None)

In [9]:
create_report(result_2019)

The statistical analysis was conducted for 14 populations with 8 paired samples.
The family-wise significance level of the tests is alpha=0.050.
We rejected the null hypothesis that the population is normal for the population db14 (p=0.000). Therefore, we assume that not all populations are normal.
Because we have more than two populations and the populations and one of them is not normal, we use the non-parametric Friedman test as omnibus test to determine if there are any significant differences between the median values of the populations. We use the post-hoc Nemenyi test to infer which differences are significant. We report the median (MD), the median absolute deviation (MAD) and the mean rank (MR) among all populations over the samples. Differences between populations are significant, if the difference of the mean rank is greater than the critical distance CD=7.015 of the Nemenyi test.
We failed to reject the null hypothesis (p=0.249) of the Friedman test that there is no difference in the central tendency of the populations db8 (MD=0.063+-0.013, MAD=0.002, MR=4.750), db6 (MD=0.066+-0.005, MAD=0.004, MR=5.000), db18 (MD=0.066+-0.017, MAD=0.005, MR=6.250), db24 (MD=0.067+-0.006, MAD=0.002, MR=6.375), Max (MD=0.068+-0.011, MAD=0.004, MR=7.125), db4 (MD=0.068+-0.012, MAD=0.004, MR=7.125), db26 (MD=0.069+-0.019, MAD=0.006, MR=7.250), db28 (MD=0.070+-0.009, MAD=0.005, MR=7.375), db34 (MD=0.069+-0.006, MAD=0.001, MR=7.875), db14 (MD=0.072+-0.010, MAD=0.007, MR=8.375), db38 (MD=0.070+-0.009, MAD=0.006, MR=8.500), Average (MD=0.069+-0.008, MAD=0.004, MR=8.625), db16 (MD=0.073+-0.009, MAD=0.005, MR=9.750), and db36 (MD=0.076+-0.017, MAD=0.005, MR=10.625). Therefore, we assume that there is no statistically significant difference between the median values of the populations.

In [10]:
latex_table(result_2019)

\begin{table}[h]
\centering
\begin{tabular}{lrrll}
\toprule
 & MR & MED & MAD & CI \\
\midrule
db8 & 4.750 & 0.063 & 0.002 & [0.060, 0.087] \\
db6 & 5.000 & 0.066 & 0.004 & [0.060, 0.071] \\
db18 & 6.250 & 0.066 & 0.005 & [0.055, 0.090] \\
db24 & 6.375 & 0.067 & 0.002 & [0.062, 0.075] \\
Max & 7.125 & 0.068 & 0.004 & [0.062, 0.083] \\
db4 & 7.125 & 0.068 & 0.004 & [0.059, 0.083] \\
db26 & 7.250 & 0.069 & 0.006 & [0.058, 0.095] \\
db28 & 7.375 & 0.070 & 0.005 & [0.058, 0.076] \\
db34 & 7.875 & 0.069 & 0.001 & [0.063, 0.074] \\
db14 & 8.375 & 0.072 & 0.007 & [0.060, 0.080] \\
db38 & 8.500 & 0.070 & 0.006 & [0.061, 0.080] \\
Average & 8.625 & 0.069 & 0.004 & [0.062, 0.078] \\
db16 & 9.750 & 0.073 & 0.005 & [0.064, 0.082] \\
db36 & 10.625 & 0.076 & 0.005 & [0.055, 0.088] \\
\bottomrule
\end{tabular}
\caption{Summary of populations}
\label{tbl:stat_results}
\end{table}

In [36]:
bayesian_result_2019 = autorank(
    autorank_input_2019, 
    alpha=0.05, 
    approach='bayesian', 
    rope=0.001,
    verbose=False, 
    order='ascending'
)

         meanrank    median       mad  ci_lower  ci_upper effect_size  \
db8         4.750  0.062886  0.001697  0.060341  0.086597         0.0
db6         5.000  0.066057  0.003621  0.060095  0.070787    -0.75643
db18        6.250  0.066353  0.004721  0.055067  0.089931   -0.659214
db24        6.375  0.066810  0.002367  0.062428  0.075325   -1.285378
db4         7.125  0.067971  0.003514  0.059203  0.082943     -1.2431
Max         7.125  0.068475  0.003683  0.061709  0.083105   -1.314844
db34        7.875  0.069052  0.001363   0.06254  0.073695   -2.701969
db26        7.250  0.069417  0.006035  0.057512  0.095173   -0.993765
Average     8.625  0.069421   0.00369  0.062101  0.077532   -1.534568
db28        7.375  0.069970  0.004513  0.058328   0.07574   -1.401535
db38        8.500  0.070345  0.005585  0.061033  0.079807   -1.218818
db14        8.375  0.072440  0.007172  0.060367  0.080491   -1.236454
db16        9.750  0.073420  0.004896  0.064285  0.081967   -1.939086
db36       10.625  0.075844  0.004733  0.054522  0.088363   -2.458547

          magnitude effect_size_above magnitude_above
db8      negligible               0.0      negligible
db6          medium          -0.75643          medium
db18         medium         -0.047424      negligible
db24          large         -0.082556      negligible
db4           large         -0.261399           small
Max           large         -0.094458      negligible
db34          large         -0.140076      negligible
db26          large         -0.056262      negligible
Average       large         -0.000528      negligible
db28          large         -0.089951      negligible
db38          large         -0.049701      negligible
db14          large         -0.219859           small
db16          large         -0.107619      negligible
db36          large         -0.339666           small

In [37]:
create_report(bayesian_result_2019)

The statistical analysis was conducted for 14 populations with 8 paired samples.
The family-wise significance level of the tests is alpha=0.050.
We rejected the null hypothesis that the population is normal for the population db28 (p=0.000). Therefore, we assume that not all populations are normal.
We used a bayesian signed rank test to determine differences between the mean values of the populations and report the median (MD) and the median absolute deviation (MAD) for each population. We distinguish between populations being pair-wise smaller, equal, or larger and make a decision for one of these cases if we estimate that the posterior probability is at least alpha=0.050.
We used the effect size to define the region of practical equivalence (ROPE) around the median dynamically as 0.001*gamma.
We found significant and practically relevant differences between the populations db8 (MD=0.063+-0.013, MAD=0.002), db6 (MD=0.066+-0.005, MAD=0.004), db18 (MD=0.066+-0.017, MAD=0.005), db24 (MD=0.067+-0.006, MAD=0.002), db4 (MD=0.068+-0.012, MAD=0.004), Max (MD=0.068+-0.011, MAD=0.004), db34 (MD=0.069+-0.006, MAD=0.001), db26 (MD=0.069+-0.019, MAD=0.006), Average (MD=0.069+-0.008, MAD=0.004), db28 (MD=0.070+-0.009, MAD=0.005), db38 (MD=0.070+-0.009, MAD=0.006), db14 (MD=0.072+-0.010, MAD=0.007), db16 (MD=0.073+-0.009, MAD=0.005), and db36 (MD=0.076+-0.017, MAD=0.005).
The median of the population db34 is larger than of the populations db6.
The median of the population Average is larger than of the populations db6.
The median of the population db38 is larger than of the populations db6 and db24.
The median of the population db14 is larger than of the populations db6.
The median of the population db16 is larger than of the populations db8, db6, db24, db4, and Max.
The median of the population db36 is larger than of the populations db8, db6, db18, and db34.
All other differences are inconclusive.

### ASVspoof 2021

In [11]:
result_2021 = autorank(autorank_input_2021, alpha=0.05, verbose=False, order='ascending')
print(result_2021)

         meanrank    median       mad  ci_lower  ci_upper effect_size  \
Average     5.125  0.143914  0.002692  0.139828  0.154562         0.0
db26        5.375  0.145647  0.003418  0.141074  0.162414   -0.380012
db24        5.625  0.145272  0.003678     0.141  0.160188   -0.284203
Max         6.375  0.149443  0.001437  0.142815  0.151421   -1.728485
db6         6.375  0.147952  0.003793  0.140743  0.165927   -0.827991
db18        6.625  0.147159  0.003849  0.142098  0.169489   -0.659006
db8         6.875  0.148248  0.005588  0.140276   0.17429   -0.666487
db4         7.375  0.148099  0.004495  0.142771  0.161661   -0.761874
db14        7.500  0.151097  0.002607  0.137871  0.154835    -1.82848
db34        9.000  0.152239  0.006425   0.14389  0.174561   -1.139867
db36        9.000  0.153180  0.004693  0.143292  0.193421   -1.633588
db16        9.375  0.150799   0.00568  0.143778  0.171162   -1.044931
db38        9.625  0.155299  0.006066  0.142803  0.167354   -1.636338
db28       10.750  0.154858  0.004898  0.149252  0.175745   -1.867843

          magnitude effect_size_above magnitude_above
Average  negligible               0.0      negligible
db26          small         -0.380012           small
db24          small          0.071271      negligible
Max           large         -1.007539           large
db6           large          0.350764           small
db18         medium          0.139882      negligible
db8          medium          -0.15305      negligible
db4          medium          0.019791      negligible
db14          large         -0.550284          medium
db34          large          -0.15714      negligible
db36          large         -0.112793      negligible
db16          large           0.30818           small
db38          large         -0.516515          medium
db28          large          0.053988      negligible
RankResult(rankdf=
         meanrank    median       mad  ci_lower  ci_upper effect_size  \
Average     5.125  0.143914  0.002692  0.139828  0.154562         0.0
db26        5.375  0.145647  0.003418  0.141074  0.162414   -0.380012
db24        5.625  0.145272  0.003678     0.141  0.160188   -0.284203
Max         6.375  0.149443  0.001437  0.142815  0.151421   -1.728485
db6         6.375  0.147952  0.003793  0.140743  0.165927   -0.827991
db18        6.625  0.147159  0.003849  0.142098  0.169489   -0.659006
db8         6.875  0.148248  0.005588  0.140276   0.17429   -0.666487
db4         7.375  0.148099  0.004495  0.142771  0.161661   -0.761874
db14        7.500  0.151097  0.002607  0.137871  0.154835    -1.82848
db34        9.000  0.152239  0.006425   0.14389  0.174561   -1.139867
db36        9.000  0.153180  0.004693  0.143292  0.193421   -1.633588
db16        9.375  0.150799   0.00568  0.143778  0.171162   -1.044931
db38        9.625  0.155299  0.006066  0.142803  0.167354   -1.636338
db28       10.750  0.154858  0.004898  0.149252  0.175745   -1.867843

          magnitude effect_size_above magnitude_above
Average  negligible               0.0      negligible
db26          small         -0.380012           small
db24          small          0.071271      negligible
Max           large         -1.007539           large
db6           large          0.350764           small
db18         medium          0.139882      negligible
db8          medium          -0.15305      negligible
db4          medium          0.019791      negligible
db14          large         -0.550284          medium
db34          large          -0.15714      negligible
db36          large         -0.112793      negligible
db16          large           0.30818           small
db38          large         -0.516515          medium
db28          large          0.053988      negligible
pvalue=0.13944073198004597
cd=7.014879480298086
omnibus=friedman
posthoc=nemenyi
all_normal=False
pvals_shapiro=[np.float64(0.09710633619357739), np.float64(0.089371789308346), np.float64(0.39236845190143194), np.float64(0.12812521562594803), np.float64(0.26116402535156025), np.float64(0.0513142691203219), np.float64(0.053065229368542806), np.float64(0.07871039915310402), np.float64(0.003373998390161879), np.float64(0.596267195201193), np.float64(0.20108002307804484), np.float64(0.14390019313824226), np.float64(0.07083871039097528), np.float64(0.07358012119770546)]
homoscedastic=True
pval_homogeneity=0.7551561436984711
homogeneity_test=levene
alpha=0.05
alpha_normality=0.0035714285714285718
num_samples=8
posterior_matrix=
None
decision_matrix=
None
rope=None
rope_mode=None
effect_size=akinshin_gamma
force_mode=None)

In [12]:
create_report(result_2021)

The statistical analysis was conducted for 14 populations with 8 paired samples.
The family-wise significance level of the tests is alpha=0.050.
We rejected the null hypothesis that the population is normal for the population db14 (p=0.003). Therefore, we assume that not all populations are normal.
Because we have more than two populations and the populations and one of them is not normal, we use the non-parametric Friedman test as omnibus test to determine if there are any significant differences between the median values of the populations. We use the post-hoc Nemenyi test to infer which differences are significant. We report the median (MD), the median absolute deviation (MAD) and the mean rank (MR) among all populations over the samples. Differences between populations are significant, if the difference of the mean rank is greater than the critical distance CD=7.015 of the Nemenyi test.
We failed to reject the null hypothesis (p=0.139) of the Friedman test that there is no difference in the central tendency of the populations Average (MD=0.144+-0.007, MAD=0.003, MR=5.125), db26 (MD=0.146+-0.011, MAD=0.003, MR=5.375), db24 (MD=0.145+-0.010, MAD=0.004, MR=5.625), Max (MD=0.149+-0.004, MAD=0.001, MR=6.375), db6 (MD=0.148+-0.013, MAD=0.004, MR=6.375), db18 (MD=0.147+-0.014, MAD=0.004, MR=6.625), db8 (MD=0.148+-0.017, MAD=0.006, MR=6.875), db4 (MD=0.148+-0.009, MAD=0.004, MR=7.375), db14 (MD=0.151+-0.008, MAD=0.003, MR=7.500), db34 (MD=0.152+-0.015, MAD=0.006, MR=9.000), db36 (MD=0.153+-0.025, MAD=0.005, MR=9.000), db16 (MD=0.151+-0.014, MAD=0.006, MR=9.375), db38 (MD=0.155+-0.012, MAD=0.006, MR=9.625), and db28 (MD=0.155+-0.013, MAD=0.005, MR=10.750). Therefore, we assume that there is no statistically significant difference between the median values of the populations.

In [13]:
latex_table(result_2021)

\begin{table}[h]
\centering
\begin{tabular}{lrrll}
\toprule
 & MR & MED & MAD & CI \\
\midrule
Average & 5.125 & 0.144 & 0.003 & [0.140, 0.155] \\
db26 & 5.375 & 0.146 & 0.003 & [0.141, 0.162] \\
db24 & 5.625 & 0.145 & 0.004 & [0.141, 0.160] \\
Max & 6.375 & 0.149 & 0.001 & [0.143, 0.151] \\
db6 & 6.375 & 0.148 & 0.004 & [0.141, 0.166] \\
db18 & 6.625 & 0.147 & 0.004 & [0.142, 0.169] \\
db8 & 6.875 & 0.148 & 0.006 & [0.140, 0.174] \\
db4 & 7.375 & 0.148 & 0.004 & [0.143, 0.162] \\
db14 & 7.500 & 0.151 & 0.003 & [0.138, 0.155] \\
db34 & 9.000 & 0.152 & 0.006 & [0.144, 0.175] \\
db36 & 9.000 & 0.153 & 0.005 & [0.143, 0.193] \\
db16 & 9.375 & 0.151 & 0.006 & [0.144, 0.171] \\
db38 & 9.625 & 0.155 & 0.006 & [0.143, 0.167] \\
db28 & 10.750 & 0.155 & 0.005 & [0.149, 0.176] \\
\bottomrule
\end{tabular}
\caption{Summary of populations}
\label{tbl:stat_results}
\end{table}

In [38]:
bayesian_result_2021 = autorank(
    autorank_input_2021, 
    alpha=0.05, 
    approach='bayesian', 
    rope=0.001,
    verbose=False, 
    order='ascending'
)

         meanrank    median       mad  ci_lower  ci_upper effect_size  \
Average     5.125  0.143914  0.002692  0.139828  0.154562         0.0
db24        5.625  0.145272  0.003678     0.141  0.160188   -0.284203
db26        5.375  0.145647  0.003418  0.141074  0.162414   -0.380012
db18        6.625  0.147159  0.003849  0.142098  0.169489   -0.659006
db6         6.375  0.147952  0.003793  0.140743  0.165927   -0.827991
db4         7.375  0.148099  0.004495  0.142771  0.161661   -0.761874
db8         6.875  0.148248  0.005588  0.140276   0.17429   -0.666487
Max         6.375  0.149443  0.001437  0.142815  0.151421   -1.728485
db16        9.375  0.150799   0.00568  0.143778  0.171162   -1.044931
db14        7.500  0.151097  0.002607  0.137871  0.154835    -1.82848
db34        9.000  0.152239  0.006425   0.14389  0.174561   -1.139867
db36        9.000  0.153180  0.004693  0.143292  0.193421   -1.633588
db28       10.750  0.154858  0.004898  0.149252  0.175745   -1.867843
db38        9.625  0.155299  0.006066  0.142803  0.167354   -1.636338

          magnitude effect_size_above magnitude_above
Average  negligible               0.0      negligible
db24          small         -0.284203           small
db26          small         -0.071271      negligible
db18         medium         -0.280151           small
db6           large         -0.139882      negligible
db4          medium         -0.023904      negligible
db8          medium         -0.019791      negligible
Max           large         -0.197639      negligible
db16          large         -0.220809           small
db14          large         -0.045372      negligible
db34          large          -0.15714      negligible
db36          large         -0.112793      negligible
db28          large         -0.235984           small
db38          large         -0.053988      negligible

In [39]:
create_report(bayesian_result_2021)

The statistical analysis was conducted for 14 populations with 8 paired samples.
The family-wise significance level of the tests is alpha=0.050.
We rejected the null hypothesis that the population is normal for the population db26 (p=0.003). Therefore, we assume that not all populations are normal.
We used a bayesian signed rank test to determine differences between the mean values of the populations and report the median (MD) and the median absolute deviation (MAD) for each population. We distinguish between populations being pair-wise smaller, equal, or larger and make a decision for one of these cases if we estimate that the posterior probability is at least alpha=0.050.
We used the effect size to define the region of practical equivalence (ROPE) around the median dynamically as 0.001*gamma.
We found significant and practically relevant differences between the populations Average (MD=0.144+-0.007, MAD=0.003), db24 (MD=0.145+-0.010, MAD=0.004), db26 (MD=0.146+-0.011, MAD=0.003), db18 (MD=0.147+-0.014, MAD=0.004), db6 (MD=0.148+-0.013, MAD=0.004), db4 (MD=0.148+-0.009, MAD=0.004), db8 (MD=0.148+-0.017, MAD=0.006), Max (MD=0.149+-0.004, MAD=0.001), db16 (MD=0.151+-0.014, MAD=0.006), db14 (MD=0.151+-0.008, MAD=0.003), db34 (MD=0.152+-0.015, MAD=0.006), db36 (MD=0.153+-0.025, MAD=0.005), db28 (MD=0.155+-0.013, MAD=0.005), and db38 (MD=0.155+-0.012, MAD=0.006).
The median of the population db16 is larger than of the populations Average, db24, and db6.
The median of the population db34 is larger than of the populations Average, db24, db26, and Max.
The median of the population db36 is larger than of the populations Average and Max.
The median of the population db28 is larger than of the populations Average, db24, db26, db6, Max, and db14.
The median of the population db38 is larger than of the populations Average, db24, Max, and db14.
All other differences are inconclusive.

## Friedman Test

### ASVspoof 2019

In [14]:
average_2019 = autorank_input_2019["Average"]
max_2019 = autorank_input_2019["Max"]
db4_2019 = autorank_input_2019["db4"]
db6_2019 = autorank_input_2019["db6"]
db8_2019 = autorank_input_2019["db8"]
db14_2019 = autorank_input_2019["db14"]
db16_2019 = autorank_input_2019["db16"]
db18_2019 = autorank_input_2019["db18"]
db24_2019 = autorank_input_2019["db24"]
db26_2019 = autorank_input_2019["db26"]
db28_2019 = autorank_input_2019["db28"]
db34_2019 = autorank_input_2019["db34"]
db36_2019 = autorank_input_2019["db36"]
db38_2019 = autorank_input_2019["db38"]

In [15]:
friedman_2019 = stats.friedmanchisquare(
    average_2019, max_2019, db4_2019, db6_2019, db8_2019, db14_2019, db16_2019, db18_2019,
    db24_2019, db26_2019, db28_2019, db34_2019, db36_2019, db38_2019,
)
friedman_2019

FriedmanchisquareResult(statistic=np.float64(16.0), pvalue=np.float64(0.24912985116586753))

### ASVspoof 2021

In [16]:
average_2021 = autorank_input_2021["Average"]
max_2021 = autorank_input_2021["Max"]
db4_2021 = autorank_input_2021["db4"]
db6_2021 = autorank_input_2021["db6"]
db8_2021 = autorank_input_2021["db8"]
db14_2021 = autorank_input_2021["db14"]
db16_2021 = autorank_input_2021["db16"]
db18_2021 = autorank_input_2021["db18"]
db24_2021 = autorank_input_2021["db24"]
db26_2021 = autorank_input_2021["db26"]
db28_2021 = autorank_input_2021["db28"]
db34_2021 = autorank_input_2021["db34"]
db36_2021 = autorank_input_2021["db36"]
db38_2021 = autorank_input_2021["db38"]

In [17]:
friedman_2021 = stats.friedmanchisquare(
    average_2021, max_2021, db4_2021, db6_2021, db8_2021, db14_2021, db16_2021, db18_2021,
    db24_2021, db26_2021, db28_2021, db34_2021, db36_2021, db38_2021,
)
friedman_2021

FriedmanchisquareResult(statistic=np.float64(18.5), pvalue=np.float64(0.13944073198004597))

## Nemenyi Test

### ASVspoof 2019

In [18]:
data_2019 = np.array([average_2019, max_2019, db4_2019, db6_2019, db8_2019, db14_2019, db16_2019, db18_2019,
    db24_2019, db26_2019, db28_2019, db34_2019, db36_2019, db38_2019])

In [19]:
sp.posthoc_nemenyi_friedman(data_2019.T)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.000000,0.999984,0.999984,0.904436,0.851779,1.000000,1.000000,0.997525,0.998574,0.999994,0.999998,1.000000,0.999592,1.000000
1,0.999984,1.000000,1.000000,0.999217,0.997525,0.999998,0.993412,1.000000,1.000000,1.000000,1.000000,1.000000,0.925451,0.999994
2,0.999984,1.000000,1.000000,0.999217,0.997525,0.999998,0.993412,1.000000,1.000000,1.000000,1.000000,1.000000,0.925451,0.999994
3,0.904436,0.999217,0.999217,1.000000,1.000000,0.943059,0.576739,0.999998,0.999994,0.998574,0.997525,0.984814,0.284860,0.925451
4,0.851779,0.997525,0.997525,1.000000,1.000000,0.904436,0.487166,0.999984,0.999960,0.995882,0.993412,0.969013,0.219782,0.879885
5,1.000000,0.999998,0.999998,0.943059,0.904436,1.000000,0.999994,0.999217,0.999592,1.000000,1.000000,1.000000,0.998574,1.000000
6,1.000000,0.993412,0.993412,0.576739,0.487166,0.999994,1.000000,0.925451,0.943059,0.995882,0.997525,0.999799,1.000000,0.999998
7,0.997525,1.000000,1.000000,0.999998,0.999984,0.999217,0.925451,1.000000,1.000000,1.000000,1.000000,0.999960,0.707391,0.998574
8,0.998574,1.000000,1.000000,0.999994,0.999960,0.999592,0.943059,1.000000,1.000000,1.000000,1.000000,0.999984,0.747650,0.999217
9,0.999994,1.000000,1.000000,0.998574,0.995882,1.000000,0.995882,1.000000,1.000000,1.000000,1.000000,1.000000,0.943059,0.999998
10,0.999998,1.000000,1.000000,0.997525,0.993412,1.000000,0.997525,1.000000,1.000000,1.000000,1.000000,1.000000,0.957481,1.000000
11,1.000000,1.000000,1.000000,0.984814,0.969013,1.000000,0.999799,0.999960,0.999984,1.000000,1.000000,1.000000,0.989831,1.000000
12,0.999592,0.925451,0.925451,0.284860,0.219782,0.998574,1.000000,0.707391,0.747650,0.943059,0.957481,0.989831,1.000000,0.999217
13,1.000000,0.999994,0.999994,0.925451,0.879885,1.000000,0.999998,0.998574,0.999217,0.999998,1.000000,1.000000,0.999217,1.000000

### ASVspoof 2021

In [20]:
data_2021 = np.array([average_2021, max_2021, db4_2021, db6_2021, db8_2021, db14_2021, db16_2021, db18_2021,
    db24_2021, db26_2021, db28_2021, db34_2021, db36_2021, db38_2021])

In [21]:
sp.posthoc_nemenyi_friedman(data_2021.T)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.000000,0.999998,0.998574,0.999998,0.999907,0.997525,0.747650,0.999984,1.000000,1.000000,0.284860,0.851779,0.851779,0.665114
1,0.999998,1.000000,1.000000,1.000000,1.000000,1.000000,0.977999,1.000000,1.000000,1.000000,0.707391,0.993412,0.993412,0.957481
2,0.998574,1.000000,1.000000,1.000000,1.000000,1.000000,0.999592,1.000000,0.999907,0.999592,0.943059,0.999960,0.999960,0.998574
3,0.999998,1.000000,1.000000,1.000000,1.000000,1.000000,0.977999,1.000000,1.000000,1.000000,0.707391,0.993412,0.993412,0.957481
4,0.999907,1.000000,1.000000,1.000000,1.000000,1.000000,0.995882,1.000000,0.999998,0.999984,0.851779,0.999217,0.999217,0.989831
5,0.997525,1.000000,1.000000,1.000000,1.000000,1.000000,0.999799,1.000000,0.999799,0.999217,0.957481,0.999984,0.999984,0.999217
6,0.747650,0.977999,0.999592,0.977999,0.995882,0.999799,1.000000,0.989831,0.879885,0.820212,0.999994,1.000000,1.000000,1.000000
7,0.999984,1.000000,1.000000,1.000000,1.000000,1.000000,0.989831,1.000000,1.000000,0.999998,0.785396,0.997525,0.997525,0.977999
8,1.000000,1.000000,0.999907,1.000000,0.999998,0.999799,0.879885,1.000000,1.000000,1.000000,0.443335,0.943059,0.943059,0.820212
9,1.000000,1.000000,0.999592,1.000000,0.999984,0.999217,0.820212,0.999998,1.000000,1.000000,0.359997,0.904436,0.904436,0.747650
10,0.284860,0.707391,0.943059,0.707391,0.851779,0.957481,0.999994,0.785396,0.443335,0.359997,1.000000,0.999907,0.999907,1.000000
11,0.851779,0.993412,0.999960,0.993412,0.999217,0.999984,1.000000,0.997525,0.943059,0.904436,0.999907,1.000000,1.000000,1.000000
12,0.851779,0.993412,0.999960,0.993412,0.999217,0.999984,1.000000,0.997525,0.943059,0.904436,0.999907,1.000000,1.000000,1.000000
13,0.665114,0.957481,0.998574,0.957481,0.989831,0.999217,1.000000,0.977999,0.820212,0.747650,1.000000,1.000000,1.000000,1.000000

##

In [22]:
autorank_input_2019

wavelet_family,Average,Max,db14,db16,db18,db24,db26,db28,db34,db36,db38,db4,db6,db8
seed,,,,,,,,,,,,,,
32,0.070981,0.083105,0.061163,0.081967,0.063248,0.067952,0.061456,0.069782,0.069913,0.077255,0.067299,0.082943,0.061863,0.062971
42,0.062101,0.068806,0.074591,0.076720,0.060847,0.069065,0.058192,0.062396,0.068282,0.074434,0.074825,0.059203,0.070787,0.086597
49,0.072603,0.068113,0.070289,0.081052,0.067983,0.075325,0.073525,0.070158,0.062540,0.054522,0.079807,0.072480,0.065961,0.061856
51,0.064039,0.069605,0.060367,0.067573,0.078722,0.062428,0.073148,0.058328,0.067186,0.083073,0.068525,0.060487,0.060095,0.061191
69,0.073295,0.068145,0.080060,0.069474,0.055067,0.064332,0.057512,0.075740,0.073011,0.070427,0.061033,0.067299,0.062939,0.060341
73,0.067860,0.061709,0.065715,0.070292,0.089931,0.063630,0.095173,0.072665,0.068345,0.079810,0.072164,0.070489,0.066153,0.066349
99,0.065914,0.062240,0.080491,0.064285,0.064723,0.065669,0.067998,0.065368,0.069759,0.071796,0.063655,0.068644,0.066207,0.064585
101,0.077532,0.075325,0.077908,0.076547,0.070289,0.068691,0.070835,0.074395,0.073695,0.088363,0.077223,0.066076,0.070182,0.062801

In [23]:
rankings_2019 = {
    seed: list(autorank_input_2019.loc[seed].sort_values().index)
    for seed in autorank_input_2019.index
}

columns = autorank_input_2019.columns

In [24]:
dataset = {
    i: [] for i in columns
}

In [25]:
for i in columns:
    for j in rankings_2019.values():
        dataset[i].append(j.index(i) + 1)

In [28]:
ranking = pd.DataFrame(dataset, index=["32", "42", "49", "51", "69", "73", "99", "101"])
ranking.index.name = "seed"
ranking.columns.name = "wavelet_family"
ranking.loc["Average"] = list(ranking.mean())

ranking

wavelet_family,Average,Max,db14,db16,db18,db24,db26,db28,db34,db36,db38,db4,db6,db8
seed,,,,,,,,,,,,,,
32,10.000,14.000,1.000,12.00,5.00,7.000,2.00,8.000,9.000,11.000,6.0,13.000,3.0,4.00
42,4.000,7.000,11.000,13.00,3.00,8.000,1.00,5.000,6.000,10.000,12.0,2.000,9.0,14.00
49,10.000,6.000,8.000,14.00,5.00,12.000,11.00,7.000,3.000,1.000,13.0,9.000,4.0,2.00
51,7.000,11.000,3.000,9.00,13.00,6.000,12.00,1.000,8.000,14.000,10.0,4.000,2.0,5.00
69,12.000,8.000,14.000,9.00,1.00,6.000,2.00,13.000,11.000,10.000,4.0,7.000,5.0,3.00
73,6.000,1.000,3.000,8.00,13.00,2.000,14.00,11.000,7.000,12.000,10.0,9.000,4.0,5.00
99,8.000,1.000,14.000,3.00,5.00,7.000,10.00,6.000,12.000,13.000,2.0,11.000,9.0,4.00
101,12.000,9.000,13.000,10.00,5.00,3.000,6.00,8.000,7.000,14.000,11.0,2.000,4.0,1.00
Average,8.625,7.125,8.375,9.75,6.25,6.375,7.25,7.375,7.875,10.625,8.5,7.125,5.0,4.75

In [29]:
N = len(rankings_2019)
k = len(rankings_2019[42])

chi_square = ((12 * N) / (k * (k+1))) * sum([(ranking.iloc[:, i]["Average"])**2 - ((k*(k+1)**2)/4) for i in range(1, k)])
chi_square

np.float64(-4338.007142857143)

In [30]:
FF = ((N-1) * chi_square**2) / (N * (k-1) - chi_square**2)
FF

np.float64(-7.000038685948907)